services:
    # Keycloak service for authentication
    #
    keycloak:
        image: jboss/keycloak:12.0.4
        environment:
            # Variables read from local .env file
            - KEYCLOAK_USER=${KEYCLOAK_USER}
            - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
        #ports:
            # Not exposed to host
            #- "8080"
            #- "8443" 
            #- "8990"
            #- "8993" 
        restart: unless-stopped
        volumes:
            - keycloak_data:/opt/jboss/keycloak/standalone/data
        networks:
            - front_tier

    # Web server for Patient Registration vue app files.
    #
    registration:
        build: ../PatientRegistrationApp
        depends_on:
            - keycloak
        restart: unless-stopped
        networks:
            - front_tier

    # Web server for Point of Disensing vue app files.
    #
    pod:
        build: ../PointOfDispensingApp
        depends_on:
            - keycloak
        restart: unless-stopped
        networks:
            - front_tier

    # NextGen Connect Integration Engine (formerly Mirth Connect)
    #
    mirth:
        image: nextgenhealthcare/connect:3.10
        #ports:
            # Not exposed to host
            #- "8444" 
        restart: unless-stopped
        networks:
            - back_tier

    # Node server for broker service.
    #
    broker:
        build: ../broker
        #ports:
            # Should not be exposed to host
            #- "3000"
        depends_on:
            - keycloak
            - hapi
            - mirth
        restart: unless-stopped
        networks:
            - front_tier
            - back_tier

    # Database for HAPI FHIR service
    #
    hapi-db:
        image: postgres
        environment:
            # Variables read from local .env file
            - POSTGRES_DB=${HAPI_DB_NAME}
            - POSTGRES_USER=${HAPI_DB_USERNAME}
            - POSTGRES_PASSWORD=${HAPI_DB_PASSWORD}
        volumes:
            #- hapi_db_config:/etc/postgresql
            #- hapi_db_logs:/var/log/postgresql
            - hapi_db_data:/var/lib/postgresql/data
        #ports:
            # Should not be exposed to host
            #- "5432"
        restart: unless-stopped
        networks:
            - back_tier

    # HAPI FHIR service
    #
    hapi:
        image: hapiproject/hapi:v5.0.0
        volumes:
            - ./hapi.properties:/etc/hapi/hapi.properties
            - hapi_data:/data/hapi
        environment:
            - JAVA_OPTS=-Dhapi.properties=/etc/hapi/hapi.properties
        #ports:
            # Not exposed to host
            #- "8080"
        depends_on:
            - hapi-db
        restart: unless-stopped
        networks:
            - back_tier

    # proxy handle routing requests to the appropriate back-end service, as
    # defined in the nginx.conf. 
    #
    # It will also handle enabling https (and forcing http to https).
    #
    nginx: 
        image: nginx:stable-alpine
        volumes:
            - ${PROXY_VOLUME_MAP1}
            - ${PROXY_VOLUME_MAP2}
            - ${PROXY_VOLUME_MAP3}
        ports:
            - "${PROXY_HTTP_PORT}:80"
            - "${PROXY_HTTPS_PORT}:443"
        depends_on:
            - keycloak
            - broker
            - pod
            - registration
        restart: unless-stopped
        networks:
            - front_tier

# Only the front_tier network should have ports exposed to the host.
#
networks:
    front_tier:
    back_tier:

# Volumes for data that must be preserved if containers stop/re-start.
#
volumes:
    keycloak_data:
    hapi_data:
    hapi_db_data:
