services:
    # proxy handle routing requests to the appropriate back-end service, as
    # defined in the nginx.conf. 
    #
    # It will also handle enabling https (and forcing http to https).
    #
    nginx: 
        image: nginx:stable-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./sandbox.crt:/etc/nginx/sandbox.crt
            - ./sandbox.key:/etc/nginx/sandbox.key
        ports:
            - "80:80"
            - "443:443"
        networks:
            - front_tier
            - back_tier

    # Web server for Patient Registration vue app files.
    #
    registration:
        build: ../PatientRegistrationApp
        networks:
            - back_tier

    # Web server for POD vue app files.
    #
    pod:
        build: ../PointOfDispensingApp
        networks:
            - back_tier

    # Node server for broker service.
    #
    broker:
        build: ../broker
        environment:
            # +TODO+ Get from .env file
            - DB_NAME=massvaxx
            - DB_DIALECT=postgres
            - DB_HOST=broker-db
            - DB_PORT=5432
            - DB_USERNAME=massvaxxuser
            - DB_PASSWORD=__TBD__
        #ports:
            # Should not be exposed to host
            #- "3000"
        networks:
            - back_tier

    # Database service for broker
    #
    broker-db:
        build: ../broker_db
        environment:
            # +TODO+ Get password in .env file (for massvaxxadmin super user account)
            - POSTGRES_PASSWORD=massvaxxadmin
        volumes:
            #- broker_db_config:/etc/postgresql
            #- broker_db_logs:/var/log/postgresql
            - broker_db_data:/var/lib/postgresql/data
        #ports:
            # Should not be exposed to host
            #- "5432"
        networks:
            - back_tier

    # HAPI FHIR service
    # +TODO+ Update to use PostgreSQL for production deloyment 
    #
    hapi:
        image: hapiproject/hapi:v5.0.0
        volumes:
            - hapi_data:/data/hapi
        #environment:
        #    - JAVA_OPTS=-Dhapi.properties=/data/hapi/hapi.properties
        #ports:
            # Not exposed to host
            #- "8080"
        networks:
            - back_tier
    
    # NextGen Connect Integration Engine (formerly Mirth Connect)
    #
    mirth:
        image: nextgenhealthcare/connect:3.10
        #ports:
            # Not exposed to host
            #- "8444" 
        networks:
            - back_tier

# Only the front_tier network should have ports exposed to the host.
#
networks:
    front_tier:
    back_tier:

# Volumes for data that must be preserved if containers stop/re-start.
#
volumes:
    #broker_db_config:
    #broker_db_logs:
    broker_db_data:
    hapi_data:
