version: '3'

services:
    hapi:
        build: './hapi_fhir'
        ports:
            - "8080:8080"
        volumes:
            - ./hapi_fhir/data/hapi:/data/hapi
    db:
        build: './broker_db'
        ports:
            - "5432:5432"
        environment:
            # Variables read from local .env file
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data/
# named volume for persistent database
volumes:
    pgdata:
