kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  replicas: 1
  selector:
      matchLabels:
          app: server
          role: backend
          env: production
  template:
    metadata:
      name: backend
      labels:
        app: server
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: pethogya/testrepo:server
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        #readinessProbe:
         # httpGet:
          #  path: /healthz
           # port: 8080
        #command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080