export default {
  registrationPages: {
    GREETING_PAGE: 1,
    SINGLE_PATIENT_HOME_ADDRESS_PAGE: 2,
    SINGLE_PATIENT_CONTACT_INFO_PAGE: 3,
    SINGLE_PATIENT_PERSONAL_INFO_PAGE: 4,
    SINGLE_PATIENT_SCREENING_PAGE: 5,
    SINGLE_PATIENT_EMERGENCY_CONTACT_PAGE: 6,
    SINGLE_PATIENT_REVIEW_SUBMIT_PAGE: 7,
    SINGLE_PATIENT_FOLLOWUP_PAGE: 8,
    HOUSEHOLD_REGISTER_NUMBER_PAGE: 2,
    HOUSEHOLD_HOME_ADDRESS_PAGE: 3,
    HOUSEHOLD_CONTACT_INFO_PAGE: 4,
    HOUSEHOLD_PERSONAL_INFO_PATIENT_1_PAGE: 5,
    HOUSEHOLD_EMERGENCY_CONTACT_PAGE: 6,
    HOUSEHOLD_PERSONAL_INFO_PATIENT_N_PAGE: 7,
    HOUSEHOLD_REVIEW_SUBMIT_PAGE: 8,
    HOUSEHOLD_FOLLOWUP_PAGE: 9,
  },

  selectedRegistrationPath: {
    NO_PATH_SELECTED: 0,
    SINGLE_PATIENT_REGISTRATION_PATH: 1,
    HOUSEHOLD_REGISTRATION_PATH: 2,
  },
  FontSizes: {
    FONT_SMALL: "1em",
    FONT_MEDIUM: "1.5em",
    FONT_LARGE: "3em",
  },
};
