name: Format (prettier)

# Controls when the action will run.
on:
  push:
    branches: [Development]
  pull_request_target:
    paths: "**/*.{css,js,vue}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prettier:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout head branch of pull request
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      # Clean-install prettier
      - name: Install prettier
        run: |
          rm -f package.json
          yarn init -yp
          yarn add --dev --exact --ignore-scripts prettier@2.2.1

      # Do not format workflow files. Modifying workflow files requires additional permissions
      - name: Format prettier
        run: yarn run prettier --write '**/*.{css,js,vue}'

      # Post-install cleanup
      - name: Post install
        run: |
          git clean -df
          git restore node_modules/* || :
          git restore package.json || :
          git restore yarn.lock || :

      # Commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: Apply prettier changes
